rd /s /q .vs
rd /s /q Cavern\bin
rd /s /q Cavern\obj
rd /s /q Cavern.Format\bin
rd /s /q Cavern.Format\obj
rd /s /q Cavern.QuickEQ\bin
rd /s /q Cavern.QuickEQ\obj
rd /s /q Cavern.QuickEQ.Format\bin
rd /s /q Cavern.QuickEQ.Format\obj
rd /s /q "CavernUnity DLL\bin"
rd /s /q "CavernUnity DLL\obj"
rd /s /q "CavernUnity.WebGL\bin"
rd /s /q "CavernUnity.WebGL\obj"
rd /s /q CavernSamples\.vs
rd /s /q CavernSamples\Benchmark\bin
rd /s /q CavernSamples\Benchmark\obj
rd /s /q CavernSamples\Cavern.WPF\bin
rd /s /q CavernSamples\Cavern.WPF\obj
rd /s /q CavernSamples\CavernizeGUI\bin
rd /s /q CavernSamples\CavernizeGUI\obj
rd /s /q CavernSamples\CavernizeLive\bin
rd /s /q CavernSamples\CavernizeLive\obj
rd /s /q CavernSamples\Deconvolver\bin
rd /s /q CavernSamples\Deconvolver\obj
rd /s /q CavernSamples\EnhancedAC3Merger\bin
rd /s /q CavernSamples\EnhancedAC3Merger\obj
rd /s /q CavernSamples\EQAPOtoFIR\bin
rd /s /q CavernSamples\EQAPOtoFIR\obj
rd /s /q CavernSamples\HRTFSetImporter\bin
rd /s /q CavernSamples\HRTFSetImporter\obj
rd /s /q CavernSamples\QuickEQResultMerger\bin
rd /s /q CavernSamples\QuickEQResultMerger\obj
rd /s /q CavernSamples\WAVChannelReorderer\bin
rd /s /q CavernSamples\WAVChannelReorderer\obj
rd /s /q CavernSamples\WavefrontSimulator\bin
rd /s /q CavernSamples\WavefrontSimulator\obj
rd /s /q TestResults
rd /s /q Tests\Test.Cavern\bin
rd /s /q Tests\Test.Cavern\obj
rd /s /q Tests\Test.Cavern.Format\bin
rd /s /q Tests\Test.Cavern.Format\obj
rd /s /q Tests\Test.Cavern.QuickEQ\bin
rd /s /q Tests\Test.Cavern.QuickEQ\obj
pause