//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CavernizeGUI.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class UpmixingSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UpmixingSettings defaultInstance = ((UpmixingSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UpmixingSettings())));
        
        public static UpmixingSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatrixUpmix {
            get {
                return ((bool)(this["MatrixUpmix"]));
            }
            set {
                this["MatrixUpmix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cavernize {
            get {
                return ((bool)(this["Cavernize"]));
            }
            set {
                this["Cavernize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public float Effect {
            get {
                return ((float)(this["Effect"]));
            }
            set {
                this["Effect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public float Smoothness {
            get {
                return ((float)(this["Smoothness"]));
            }
            set {
                this["Smoothness"] = value;
            }
        }
    }
}
